server:
  port: 4000

logging:
  level:
    reactor.netty.http.server.HttpServerOperations: ERROR
    reactor.netty: ERROR
    io.netty: ERROR
    dev.nelit.server: DEBUG

spring:
  application:
    name: server

  sql:
    init:
      mode: always

  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
#        password: ${REDIS_PASSWORD}
#        database: ${REDIS_DATABASE}

#  main:
#    allow-bean-definition-overriding: true

cors:
  api-key: ${API_KEY}
  allowed-origins:
    - http://localhost:3000


bot:
  token: ${TELEGRAM_BOT_TOKEN}


jwt:
  secret: BPQ4uUaYXzhDwqaQ7zohUophwucdExzxMPjfnexHojAfgyfD3RGumTrnFxJcrETGgMJY99UpqMzNwuFNbFHvaRAbodp6moHWhkxzUqMa2ecsZcDGykynCZQiQVbemBWR7baWXs3WVwrZa7CgXBhqCpCYg7KyqDmhwVb4h2Km2MnQLVJArW9KFo8MC2dR6YGycg8qRCNE
  token-expiration-minutes: 14400